### ISSUE TITLE
Pluralization of internationalized model names

### ISSUE THREAD

**Issue by juanedi** [manastech/listings#8]
Rails supports definining pluralized model names as follows [[source](http://guides.rubyonrails.org/i18n.html#pluralization)]:

```yaml
es:
  activerecord:
    models:
      invitation:
        one: Invitación
        other: Invitaciones
```

But right now, displaying an empty listing for such model results in the message "No se encontraron **invitacións**". Fixing this is probably just a matter of redefining `ViewHelperMethods#kind` as follows:

```ruby
def kind
  model_class.model_name.human(count: 2).downcase rescue I18n.t('listings.records')
end
```
